B_OF_BUSH	.set	0	; natives behind bushes
B_OF_TREE	.set	1	; natives in trees
B_OF_SNAKE	.set	2	; snake in jungle
B_OF_POPUP	.set	3	; popup guys in windows
B_OF_SIDER	.set	4	; sideways guys in windows
B_OF_HONEY	.set	5	; honeycombs
B_OF_CNATV	.set	6	; natives in center
B_OF_POPQUO	.set	7	; popup guys determine when to move on
B_OF_BOXERS	.set	8	; box carrying beekeepers
B_OF_BCOG	.EQU	9
B_OF_WNINJA	.EQU	10
B_OF_PILE	.EQU	10	; OK to destroy rope bridge
B_OF_MORFRS .EQU	11	; morph chamber guys
B_OF_DNINJA	.EQU	12	;Desk Ninja



M_OF_BUSH	.set	1	 ; natives behind bushes
M_OF_TREE	.set	2	 ; natives in trees
M_OF_SNAKE	.set	4	 ; snake in jungle
M_OF_POPUP	.set	8	 ; popup guys in windows
M_OF_SIDER	.set	10h ; sideways guys in windows
M_OF_HONEY	.set	20h ; honeycombs
M_OF_CNATV	.set	40h ; natives in center
M_OF_POPQUO	.set	88h ; popup guys determine when to move on	
M_OF_BOXERS	.set	100h; box carrying beekeepers
M_OF_BCOG	.EQU	200H	;Cogheads on bridge
M_OF_WNINJA	.EQU	400H	;Ninjas on walkways 
M_OF_PILE	.EQU	400h	; OK to destroy rope bridge
M_OF_MORFRS .EQU	800H	; morph chamber guys
M_OF_DNINJA	.EQU	1000H	;Desk Ninja
